#!/usr/bin/env bash
# install haproxy and load balancing

sudo apt-get update
sudo apt-get install haproxy -y

echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.229.89.226:80 check
    server web-02 54.227.3.119:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart